export enum CMS_CONTENT_TYPES {
  CONTENT_BLOCK = "contentBlock",
  HERO_IMAGE = "heroImage",
  CONTENT_IMAGE = "contentImage",
  NAVIGATION = "navigation",
  INFORMATION = "information",
  FAVICON = "favicon",
  LOGO = "logo",
  FACEBOOK = "facebook",
  INSTAGRAM = "instagram",
  UNORDEREDLIST = "unordered-list",
  ORDEREDLIST = "ordered-list",
  H1 = "heading-1",
  HYPERLINK = "hyperlink",
  HEADER_IMAGE = "headerImage",
  START_TEXT = "startpageText",
}
