export enum CMS_CONTENT_TYPES {
  CONTENT_BLOCK = "contentBlock",
  HERO_IMAGE = "heroImage",
  CONTENT_IMAGE = "contentImage",
  NAVIGATION = "navigation",
  INFORMATION = "information",
  FAVICON = "favicon",
  LOGO = "logo",
  FACEBOOK = "facebook",
  INSTAGRAM = "instagram",
  UNORDEREDLIST = "unordered-list",
  ORDEREDLIST = "ordered-list",
  H1 = "heading-1",
  H2 = "heading-2",
  H3 = "heading-3",
  H4 = "heading-4",
  H5 = "heading-5",
  H6 = "heading-6",
  HYPERLINK = "hyperlink",
  HEADER_IMAGE = "headerImage",
  START_TEXT = "startpageText",
  TITLE = "title",
  LOCATION = "location",
  ADDRESS = "address",
  MAIL = "mail",
  PHONE = "phone",
}
