name: Deployment
on:
  push:
    branches:
      - master
jobs:
  build:
    name: building for deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install # will run `yarn install` command
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: build # will run `yarn build` command
  deployment:
    runs-on: ubuntu-latest
    environment: production
    steps:
